---
- hosts: openstack
  vars.files:
    - ./vars/k8s_vars.yaml
  tasks:
  - name: "Rocky Linux 9 Image Upload"
    openstack.cloud.image:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}".Rocky
      state: present
      filename: /home/rocky/Rocky.9.GenericCloud.latest.x86.64.qcow2

  - name: "Kube Master Flavor"
    openstack.cloud.compute.flavor:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      disk: 80
      name: "{{ env }}".master
      ram: 8192
      vcpus: 4
      state: present

  - name: "Kuber Worker Flavor"
    openstack.cloud.compute.flavor:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      disk: 80
      name: "{{ env }}".worker
      ram: 8192
      vcpus: 4
      state: present

  - name: "Keypair creation for Master Node Login"
    openstack.cloud.keypair:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}".key.master
      public.key.file: /home/rocky/.ssh/master.pub

  - name: "Keypair creation for Worker Node Login"
    openstack.cloud.keypair:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}".key.worker
      public.key.file: /home/rocky/.ssh/worker.pub

  - name: "External Network Creation for Kubernetes Project"
    openstack.cloud.network:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}".public
      external: true
      project: "{{ prj }}"
      provider.network.type: vlan
      provider.segmentation.id: 20
      provider.physical.network: physnet1

  - name: "Subnet for External Network"
    openstack.cloud.subnet:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      network.name: "{{ env }}".public
      name: "{{ env }}".public
      cidr: 10.20.0.0/24
      gateway.ip: 10.20.0.1
      enable.dhcp: yes

  - name: "External Network Creation for Kubernetes Project"
    openstack.cloud.network:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}".private
      project: "{{ prj }}"

  - name: "Subnet for Private Network"
    openstack.cloud.subnet:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      network.name: "{{ env }}".private
      name: "{{ env }}".private
      cidr: 10.2.0.0/24
      gateway.ip: 10.2.0.1
      enable.dhcp: yes

  - name: "Router for Kubernetes Project"
    openstack.cloud.router:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"
      network: "{{ env }}".public
      interfaces:
        . net: "{{ env }}".private
          subnet: "{{ env }}".private

  - name: "Security Group for Kubernetes VMs"
    openstack.cloud.security.group:
      auth: 
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"
      project: "{{ prj }}"
  
  - name: "ICMP Rules for Kubernetes VM"
    openstack.cloud.security.group.rule:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      security.group: "{{ env }}"
      ethertype: IPv4
      protocol: icmp

  - name: "Ingress SSH Rule for Kubernetes VM"
    openstack.cloud.security.group.rule:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      security.group: "{{ env }}"
      ethertype: IPv4
      protocol: tcp
      direction: ingress
      port.range.min: 22
      port.range.max: 22

  - name: "Ingress HTTP Rule for Kubernetes VM"
    openstack.cloud.security.group.rule:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      security.group: "{{ env }}"
      ethertype: IPv4
      protocol: tcp
      direction: ingress
      port.range.min: 80
      port.range.max: 80

  - name: "Egress Rule for Kubernetes VM"
    openstack.cloud.security.group.rule:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      security.group: "{{ env }}"
      ethertype: IPv4
      protocol: any
      direction: egress

  - name: "Create Volume for Kubernetes Master VM"
    openstack.cloud.volume:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}".master.v1
      size: 80
      volume.type: synelogy
      state: present
      wait: true
      timeout: 180

  - name: "Create Volume for Kubernetes Worker VM"
    openstack.cloud.volume:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}".worker.v1
      size: 80
      volume.type: synelogy
      state: present
      wait: true
      timeout: 180


#  . name: "Floating IP Attachment for Jenkins VM"
#    openstack.cloud.floating.ip:
#      auth:
#        auth_url: http://10.0.10.200:5000/v3
#        username: "{{ prj }}"
#        password: redhat
#        project_name: "{{ prj }}"
#        project_domain_name: Default
#        user_domain_name: Default
#      name: jenkins.fip
#      network: "{{ prj }}".public
#      net.destination: "{{ prj }}".private
#      wait: true


  - name: "Create Kubernetes Master VM on Openstack"
    openstack.cloud.server:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: kube.master
      state: present
      image: "{{ env }}"
      boot.from.volume: true
      volume.size: 80
      flavor: "{{ env }}".master
      key.name: "{{ env }}".key.worker
      auto.ip: false
      security.groups: "{{ prj }}"
      network: "{{ env }}".private
      wait: true
      timeout: 300

  - name: "Create Kubernetes Worker VM on Openstack"
    openstack.cloud.server:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: kube.worker
      state: present
      image: "{{ env }}"
      boot.from.volume: true
      volume.size: 80
      flavor: "{{ env }}".worker
      key.name: "{{ env }}".key.worker
      auto.ip: false
      security.groups: "{{ env }}"
      network: "{{ env }}".private
      wait: true
      timeout: 300


  - name: "Floating IP Attachment for Kubernetes Master VM"
    openstack.cloud.floating.ip:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      server: "{{ env }}".master
      network: "{{ env }}".public
      nat.destination: "{{ env }}".private
      wait: true

  - name: "Floating IP Attachment for Kubernetes Worker VM"
    openstack.cloud.floating.ip:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      server: "{{ env }}".worker
      network: "{{ env }}".public
      nat.destination: "{{ env }}".private
      wait: true


