---
- hosts: openstack
  vars_files:
    - ./vars/"{ env }}"_vars.yaml
  tasks:
  - name: "Rocky Linux 9 Image Upload"
    openstack.cloud.image:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"_Rocky
      state: present
      filename: /home/rocky/Rocky-9-GenericCloud.latest.x86_64.qcow2

  - name: "Kube Master Flavor"
    openstack.cloud.compute_flavor:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      disk: 80
      name: "{{ env }}_master"
      ram: 8192
      vcpus: 4
      state: present

  - name: "Kuber Worker Flavor"
    openstack.cloud.compute_flavor:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      disk: 80
      name: "{{ env }}_worker"
      ram: 8192
      vcpus: 4
      state: present

  - name: "Keypair creation for Master Node Login"
    openstack.cloud.keypair:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"_key_master
      public_key_file: /home/rocky/.ssh/master.pub

  - name: "Keypair creation for Worker Node Login"
    openstack.cloud.keypair:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"_key_worker
      public_key_file: /home/rocky/.ssh/worker.pub

  - name: "External Network Creation for Kubernetes Project"
    openstack.cloud.network:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"_public
      external: true
      project: "{{ prj }}"
      provider_network_type: vlan
      provider_segmentation_id: 20
      provider_physical_network: physnet1

  - name: "Subnet for External Network"
    openstack.cloud.subnet:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      network_name: "{{ env }}"_public
      name: "{{ env }}"_public
      cidr: 10.20.0.0/24
      gateway_ip: 10.20.0.1
      enable_dhcp: yes

  - name: "External Network Creation for Kubernetes Project"
    openstack.cloud.network:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"_private
      project: "{{ prj }}"

  - name: "Subnet for Private Network"
    openstack.cloud.subnet:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      network_name: "{{ env }}"_private
      name: "{{ env }}"_private
      cidr: 10.2.0.0/24
      gateway_ip: 10.2.0.1
      enable_dhcp: yes

  - name: "Router for Kubernetes Project"
    openstack.cloud.router:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"
      network: "{{ env }}"_public
      interfaces:
        - net: "{{ env }}"_private
          subnet: "{{ env }}"_private

  - name: "Security Group for Kubernetes VMs"
    openstack.cloud.security_group:
      auth: 
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"
      project: "{{ prj }}"
  
  - name: "ICMP Rules for Kubernetes VM"
    openstack.cloud.security_group_rule:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      security_group: "{{ env }}"
      ethertype: IPv4
      protocol: icmp

  - name: "Ingress SSH Rule for Kubernetes VM"
    openstack.cloud.security_group_rule:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      security_group: "{{ env }}"
      ethertype: IPv4
      protocol: tcp
      direction: ingress
      port_range_min: 22
      port_range_max: 22

  - name: "Ingress HTTP Rule for Kubernetes VM"
    openstack.cloud.security_group_rule:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      security_group: "{{ env }}"
      ethertype: IPv4
      protocol: tcp
      direction: ingress
      port_range_min: 80
      port_range_max: 80

  - name: "Egress Rule for Kubernetes VM"
    openstack.cloud.security_group_rule:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      security_group: "{{ env }}"
      ethertype: IPv4
      protocol: any
      direction: egress

  - name: "Create Volume for Kubernetes Master VM"
    openstack.cloud.volume:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"_master_v1
      size: 80
      volume_type: synelogy
      state: present
      wait: true
      timeout: 180

  - name: "Create Volume for Kubernetes Worker VM"
    openstack.cloud.volume:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: "{{ env }}"_worker_v1
      size: 80
      volume_type: synelogy
      state: present
      wait: true
      timeout: 180


#  - name: "Floating IP Attachment for Jenkins VM"
#    openstack.cloud.floating_ip:
#      auth:
#        auth_url: http://10.0.10.200:5000/v3
#        username: "{{ prj }}"
#        password: redhat
#        project_name: "{{ prj }}"
#        project_domain_name: Default
#        user_domain_name: Default
#      name: jenkins_fip
#      network: "{{ prj }}"_public
#      net_destination: "{{ prj }}"_private
#      wait: true


  - name: "Create Kubernetes Master VM on Openstack"
    openstack.cloud.server:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: kube-master
      state: present
      image: "{{ env }}"
      boot_from_volume: true
      volume_size: 80
      flavor: "{{ env }}"_master
      key_name: "{{ env }}"_key_worker
      auto_ip: false
      security_groups: "{{ prj }}"
      network: "{{ env }}"_private
      wait: true
      timeout: 300

  - name: "Create Kubernetes Worker VM on Openstack"
    openstack.cloud.server:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      name: kube-worker
      state: present
      image: "{{ env }}"
      boot_from_volume: true
      volume_size: 80
      flavor: "{{ env }}"_worker
      key_name: "{{ env }}"_key_worker
      auto_ip: false
      security_groups: "{{ env }}"
      network: "{{ env }}"_private
      wait: true
      timeout: 300


  - name: "Floating IP Attachment for Kubernetes Master VM"
    openstack.cloud.floating_ip:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      server: "{{ env }}"_master
      network: "{{ env }}"_public
      nat_destination: "{{ env }}"_private
      wait: true

  - name: "Floating IP Attachment for Kubernetes Worker VM"
    openstack.cloud.floating_ip:
      auth:
        auth_url: http://10.0.10.200:5000/v3
        username: kubeuser
        password: redhat
        project_name: "{{ prj }}"
        project_domain_name: Default
        user_domain_name: Default
      server: "{{ env }}"_worker
      network: "{{ env }}"_public
      nat_destination: "{{ env }}"_private
      wait: true


