---
- hosts: openstack
  tasks:
  - name: "Rocky Linux 9 Image Upload"
    openstack.cloud.image:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      name: k8s
      state: present
      filename: /home/ubuntu/builder/builder/Rocky-9-GenericCloud-9.0-20220830.0.x86_64.qcow2

  - name: "Kube Master Flavor"
    openstack.cloud.compute_flavor:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      disk: 80
      name: k8s_master
      ram: 8192
      vcpus: 4
      state: present

  - name: "Kuber Worker Flavor"
    openstack.cloud.compute_flavor:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      disk: 80
      name: k8s_worker
      ram: 8192
      vcpus: 4
      state: present

  - name: "Keypair creation for Master Node Login"
    openstack.cloud.keypair:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      name: master_key
      public_key_file: /home/ubuntu/.ssh/master.pub

  - name: "Keypair creation for Worker Node Login"
    openstack.cloud.keypair:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      name: worker_key
      public_key_file: /home/ubuntu/.ssh/worker.pub

  - name: "External Network Creation for Kubernetes Project"
    openstack.cloud.network:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      name: k8s_public
      external: true
      project: kubernetes
      provider_network_type: vlan
      provider_segmentation_id: 20
      provider_physical_network: physnet1

  - name: "Subnet for External Network"
    openstack.cloud.subnet:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      network_name: k8s_public
      name: k8s_public
      cidr: 10.20.0.0/24
      gateway_ip: 10.20.0.1
      enable_dhcp: yes

  - name: "External Network Creation for Kubernetes Project"
    openstack.cloud.network:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      name: k8s_private
      project: kubernetes

  - name: "Subnet for Private Network"
    openstack.cloud.subnet:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      network_name: k8s_private
      name: k8s_private
      cidr: 10.2.0.0/24
      gateway_ip: 10.2.0.1
      enable_dhcp: yes

  - name: "Router for Kubernetes Project"
    openstack.cloud.router:
      auth:
        auth_url: http://10.0.10.200:35357/v3
        username: kubeuser
        password: redhat
        project_name: kubernetes
        project_domain_name: Default
        user_domain_name: Default
      name: kubernetes
      network: k8s_public
      interfaces:
        - net: k8s_private
          subnet: k8s_private
  
  

